SELECT F1.CATEGORY, F1.PRICE AS MAX_PRICE, F1.PRODUCT_NAME
FROM FOOD_PRODUCT AS F1 JOIN (
    SELECT MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS F2 ON F1.PRICE = F2.PRICE
WHERE F1.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY F1.CATEGORY
ORDER BY F1.PRICE DESC